image: Visual Studio 2019 Preview
environment:
  nodejs_version: 8
  api_key:
    secure: 5KXvde0TpDl13n+h9W2hdjdVVI/RftroHDDa+YWkyJaZTy8RPvf7Y8bGHl8HjTjG
  access_token:
    secure: 68dSm57PRA9MjV8FG4XdLZLSLgA+bWtZAyqdDfOK6KKqctopf5Op14d7aFZjttWx
install:
  - ps: Install-Product node $env:nodejs_version
  - powershell -Command 'Camille\gen; npm ci'
before_build:
  - ps: $env:api_key | Out-File Camille.Test\apikey.txt
  - ps: Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_NAME/appveyor/SetEnv.ps1" | Invoke-Expression
  - nuget restore
after_build:
  - ps: dotnet msbuild /t:build /t:pack /p:Configuration=Release /p:Version="$env:CAMI_VERSION"
artifacts:
  - path: '**\Release\*.nupkg'
    name: release
before_deploy: 
  - ps: Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_NAME/appveyor/Docs.ps1" | Invoke-Expression
deploy:
  provider: NuGet
  api_key:
    secure: Oas6wmFju8XW3kIvsrfToZ9UPwgvBSQUL6BCMCLXRuNohcUw51EiYeIo7vSS44FD
  skip_symbols: false
  artifact: release
  on: 
    CAMI_DO_DEPLOY: true