image: Visual Studio 2019 Preview
environment:
  nodejs_version: 8
  api_key:
    secure: 5KXvde0TpDl13n+h9W2hdjdVVI/RftroHDDa+YWkyJaZTy8RPvf7Y8bGHl8HjTjG
  access_token:
    secure: 68dSm57PRA9MjV8FG4XdLZLSLgA+bWtZAyqdDfOK6KKqctopf5Op14d7aFZjttWx
install:
  - ps: Install-Product node $env:nodejs_version
before_build:
  - node --version
  - npm --version
  - powershell -Command "cd Camille\gen; npm install"
  - ps: $env:api_key | Out-File Camille.Test\apikey.txt
  - nuget restore
  - ps: >-
      $env:DO_DEPLOY = (($env:APPVEYOR_REPO_COMMIT_MESSAGE -NotMatch '\[no deploy\]')
      -Or $env:APPVEYOR_SCHEDULED_BUILD)
      -And ($env:APPVEYOR_REPO_BRANCH -Eq 'Master')
      -And (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER)
after_build:
  - ps: echo $ENV:APPVEYOR_REPO_COMMIT_TIMESTAMP
  - ps: .\deploy.ps1
artifacts:
  - path: '**\*-nightly-*.nupkg'
    name: nightly
deploy:
  provider: NuGet
  api_key:
    secure: Oas6wmFju8XW3kIvsrfToZ9UPwgvBSQUL6BCMCLXRuNohcUw51EiYeIo7vSS44FD
  skip_symbols: false
  artifact: nightly #/.*\*-nightly-*.nupkg/
  on: 
    DO_DEPLOY: true
on_success:
  - ps: .\docs.ps1
