image: Visual Studio 2017
environment:
  nodejs_version: 8
  api_key:
    secure: 5KXvde0TpDl13n+h9W2hdjdVVI/RftroHDDa+YWkyJaZTy8RPvf7Y8bGHl8HjTjG
install:
  - ps: Install-Product node $env:nodejs_version
before_build:
  - node --version
  - npm --version
  - powershell -Command "cd Camille\gen; npm install"
  - ps: $env:api_key | Out-File Camille.Test\apikey.txt
  - nuget restore
after_build:
  - ps: echo $ENV:APPVEYOR_REPO_COMMIT_TIMESTAMP
  - ps: .\deploy.ps1
artifacts:
  - path: '**\*-nightly-*.nupkg'
    name: nightly
deploy:
  provider: NuGet
#  server: # remove to push to NuGet.org
  api_key:
    secure: pQn8nvprYgKNFytgH1LhrUyfuO6meVoLfbbhZYFE1neGwC7Vqesr65TwHQSYGI/o
  skip_symbols: false
#  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: nightly #/.*\*-nightly-*.nupkg/