image: Visual Studio 2017
environment:
  nodejs_version: 8
  api_key:
    secure: 5KXvde0TpDl13n+h9W2hdjdVVI/RftroHDDa+YWkyJaZTy8RPvf7Y8bGHl8HjTjG
install:
  - ps: Install-Product node $env:nodejs_version
before_build:
  - node --version
  - npm --version
  - powershell -Command "cd Camille\gen; npm install"
  - ps: $env:api_key | Out-File Camille.Test\apikey.txt
  - nuget restore
after_build:
  - ps: echo $ENV:APPVEYOR_REPO_COMMIT_TIMESTAMP
  - ps: .\deploy.ps1
artifacts:
  - path: '**\*-nightly-*.nupkg'
    name: nightly
deploy:
  provider: NuGet
  api_key:
    secure: A0rg3A+K7NxQ6022rqGmiuiR/AncTrnk5S2wJ39LzMKHlXie3yxvnudHPZrrqk93
  skip_symbols: false
  artifact: nightly #/.*\*-nightly-*.nupkg/

